CREATE TABLE IF NOT EXISTS MEMBERS
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS MOVIES
(
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    releaseDate date         NOT NULL,
    duration    INT          NOT NULL
);

CREATE TABLE IF NOT EXISTS CINEMAS
();

CREATE TABLE IF NOT EXISTS SCREENS
();

CREATE TABLE IF NOT EXISTS SEATS
();

CREATE TABLE IF NOT EXISTS SNACKS
();

CREATE TABLE IF NOT EXISTS BOOKINGS
();

CREATE TABLE IF NOT EXISTS BOOKING_ITEMS
();

CREATE TABLE IF NOT EXISTS PAYMENTS
();
